version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./:/app
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: digimed
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: grupo@priver.app
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
networks:
  backend:
    external: false
    driver: bridge
    name: digimedbackend